### ISSUE TITLE
Toggle focus on the chat box with the enter key

### ISSUE THREAD

**Issue by bdjewkes** [codeselfstudy/xp-game#37]
Switching between writing chat messages and playing the game should be as seamless as possible (and shouldn't require using the mouse. 

I suggest that pressing the enter key should focus the chat box, and that sending a message should release focus.

It could be that releasing focus when you send a message will feel bad; an alternative idea is to use Escape to release focus.

**Comment by j127** [comment]
See https://github.com/codeselfstudy/xp-game/pull/43
